### ISSUE TITLE
unable to use plugin slather inside Cocoapods

### ISSUE THREAD

**Issue by kleiberjp** [CocoaPods/Core#630]
Adding plugin slather on pod fail before install the pod install give this error:

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/kperez/rappi/ios-rappi/apps/Grability/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `open'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:33:in `new'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:33:in `block in slather_setup_for_coverage'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:31:in `each'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:31:in `slather_setup_for_coverage'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/cocoapods_plugin.rb:7:in `block in <top (required)>'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/hooks_manager.rb:115:in `each'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/hooks_manager.rb:115:in `block in run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:145:in `message'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/hooks_manager.rb:114:in `run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:632:in `run_plugins_post_install_hooks'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:607:in `perform_post_install_actions'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:165:in `install!'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/kperez/.rbenv/versions/2.6.5/bin/pod:23:in `load'
/Users/kperez/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
```

```
 pod --version
1.9.1
```

```
ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
```

**Comment by dnkoutso** [comment]
The stacktrace shows an issue with the slather plugin which is invoking Xcodeproj:
```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/kperez/rappi/ios-rappi/apps/Grability/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `open'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/xcodeproj-1.16.0/lib/xcodeproj/scheme.rb:34:in `initialize'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:33:in `new'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:33:in `block in slather_setup_for_coverage'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:31:in `each'
/Users/kperez/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/slather-2.4.8/lib/slather/project.rb:31:in `slather_setup_for_coverage'
```

I dont think this is a cocoapods issue so far.
